id = "angular"
name = "Angular"
description = "Angular Language support"
version = "0.0.2"
schema_version = 1
authors = ["nathansbradshaw"]
repository = "https://github.com/nathansbradshaw/zed-angular"
path_suffixes = ["html", "ng.html"]

[language_servers.angular]
name = "Angular Language Server"
languages = ["TypeScript", "HTML", "Angular"]
language_ids = { "Angular" = "angular", "HTML" = "html", "TypeScript" = "typescript" }
command = { extension = true }

[grammars.angular]
repository = "https://github.com/dlvandenberg/tree-sitter-angular"
commit = "820566bb4eb3d288822dbfee42417a5a9491aea6"
